### ISSUE TITLE
Different result on local test and during autograding

### ISSUE THREAD

**Issue by Hrexandro** [devadvent/puzzle-15#1]
When I run my solution locally using "npm test", all tests pass, however after upload and during autograding, it fails:

        21 |     const date = new Date(2030, 8, 20, 14, 26, 59, 0)
        22 |     const refDate = new Date(2021, 11, 15, 14, 19, 17, 0)
      > 23 |     expect(countdown(date, refDate).days).toBe(3200)

the received days are 3201. However when I try to replicate the same code uploaded as the solution and comparing the same exact date variables, the result is:
{days: 3200, hours: 23, minutes: 7, seconds: 42} //so not 3201 days

I am not sure whether this is some JS Math quirk that I fail to take into consideration, or a problem with the autograding.

I attach a txt file with my code.
[date-format.txt](https://github.com/devadvent/puzzle-15/files/7722410/date-format.txt)

**Comment by bob-fornal** [comment]
I am having the same issue. I tried this SEVEN different ways, to include using MomentJS to do the calculations.

```script
      expect(received).toBe(expected) // Object.is equality
  
      Expected: 3200
      Received: 3201
  
        21 |     const date = new Date(2030, 8, 20, 14, 26, 59, 0)
        22 |     const refDate = new Date(2021, 11, 15, 14, 19, 17, 0)
      > 23 |     expect(countdown(date, refDate).days).toBe(3200)
           |                                           ^
        24 |     expect(countdown(date, refDate).hours).toBe(23)
        25 |     expect(countdown(date, refDate).minutes).toBe(7)
        26 |     expect(countdown(date, refDate).seconds).toBe(42)
  
        at Object.<anonymous> (tests/date-format.test.js:23:43)
```

All of my iterations are available for reference.

**Comment by cswike** [comment]
Same here, returns the correct number of days locally but when run through the autograder it returns 3201 days.

Local: 
<...solution code>
const date = new Date(2030, 8, 20, 14, 26, 59, 0)
const refDate = new Date(2021, 11, 15, 14, 19, 17, 0)
console.log(countdown(date, refDate))
output: {days: 3200, hours: 23, minutes: 7, seconds: 42}

Autograder:
expect(received).toBe(expected) // Object.is equality
  
Expected: 3200
Received: 3201 
 
21 |     const date = new Date(2030, 8, 20, 14, 26, 59, 0)
22 |     const refDate = new Date(2021, 11, 15, 14, 19, 17, 0)
23 |     expect(countdown(date, refDate).days).toBe(3200)
     |                                                                    ^
24 |     expect(countdown(date, refDate).hours).toBe(23)
25 |     expect(countdown(date, refDate).minutes).toBe(7)
26 |     expect(countdown(date, refDate).seconds).toBe(42)
  
at Object.<anonymous> (tests/date-format.test.js:23:43)

**Comment by themarcba** [comment]
Thanks for notifying 😊

Yes, this is a timezone-related issue that could be fixed with Date.UTC in the tests.

To not make everyone update this, just ignore the autograde failing. If it runs locally, that's good enough for me.

I'll assume all submissions valid and check the winner's solution manually.
